#!/bin/bash

# always exit on error
set -e

echo "Install packages using apt-get"
apt-get update
apt-get -y install python3 python3-pip

echo "Updating python environment via pip"
pip3 install --upgrade pillow setuptools pip

echo "Remove pip to prevent confusion with apt-get"
apt-get -y remove python3-pip

