#!/bin/bash

# always exit on error
set -e

echo "Install packages using apt-get"
apt-get update
apt-get -y install python3 python3-pip libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-base gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly libgstreamer1.0-dev libxine2-ffmpeg libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff5-dev libx11-dev libmtdev-dev build-essential libgl1-mesa-dev libgles2-mesa-dev pulseaudio

echo "Updating python environment via pip"
pip3 install --upgrade pillow setuptools pip

echo "Install Cython in the correct version for kivy."
pip3 install -I Cython==0.24.1

echo "Installing kivy"
pip3 install kivy

echo "Remove pip to prevent confusion with apt-get"
apt-get -y remove python3-pip

