#!/bin/bash

# always exit on error
set -e

echo "[MPF-MC Installer] Install packages using apt-get"
apt-get update
apt-get -y install git libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-base gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly libgstreamer1.0-dev libxine2-ffmpeg libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff5-dev libx11-dev libmtdev-dev build-essential libgl1-mesa-dev libgles2-mesa-dev pulseaudio lsb-release

echo "[MPF-MC Installer] Install Cython in the correct version for kivy."
pip3 install -I Cython==0.27.3

echo "[MPF-MC Installer] Installing kivy stable"
pip3 install kivy==1.10.1
