#!/bin/bash

# always exit on error
set -e

echo "[MPF Installer] Install packages using apt-get"
apt-get update
apt-get -y install python3 python3-pip build-essential zlib1g-dev libjpeg-dev libtiff5-dev libtiff5-dev

echo "[MPF Installer] Updating python environment via pip (step 1/3)"
python3 -m pip install --upgrade pip

echo "[MPF Installer] Updating python environment via pip (step 2/3)"
python3 -m pip install --upgrade setuptools

echo "[MPF Installer] Updating python environment via pip (step 3/3)"
python3 -m pip install --upgrade pillow

#echo "[MPF Installer] Remove pip to prevent confusion with apt-get"
#apt-get -y remove python3-pip

