#!/bin/bash

echo "####################################################"
echo "##   IT IS NOT A GOOD IDEA TO RUN THIS AS ROOT!   ##"
echo "##   RUN AS A REGULAR USER, AND ENTER THE SUDO    ##"
echo "##   PASSWORD WHEN ASKED.                         ##"
echo "##                                                ##"                                          
echo "##  THE SCRIPT WILL ELEVATE PRIVILEGES AS NEEDED  ##"
echo "##                                                ##"
echo "##    IF YOU RAN THIS WITH SUDO, PRESS CTRL-C     ##"
echo "##         NOW AND RUN AS A NORMAL USER.          ##"
echo "####################################################"

### Choose the build you want to deploy, dev or master

echo "Choose which build of MPF you would like to deploy:"
echo ""
echo "You should probably choose 1 for master. You can easily switch later."
echo ""
echo "(Enter 1 for master, 2 for dev, or CTRL-C to quit)"
read REPLY
case $REPLY in
 	1) BRANCH="master";;
 	2) BRANCH="dev";;
esac

if [ $BRANCH != "dev" ] && [ $BRANCH != "master" ]
then
 	echo
 	echo "###################"
 	echo "Please enter 1 or 2"
 	echo "If you want to get down and dirty, you'll have to edit this script."
 	exit
fi

clear

echo
echo "[INFO] Installing prerequsites via apt-get"

sudo apt-get update
sudo apt-get -y install git-core python3-pip libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-image-dev
sudo apt-get -y install gstreamer1.0

echo
echo "[INFO] Installing prerequisites via pip"

sudo pip3 install -I cython==0.23
sudo pip3 install kivy

echo "[INFO] Installing MPF"

sudo cp 50-P-ROC.rules /etc/udev/rules.d
sudo cp 51-P3-ROC.rules /etc/udev/rules.d

mkdir ~/pinball
cd ~/pinball
git clone --branch dev https://github.com/missionpinball/mpf
git clone --branch dev https://github.com/missionpinball/mpf-mc
git clone --branch dev https://github.com/missionpinball/mpf-examples

echo "                   Installation finished."
echo "============================================================"
echo "   If you're using a P-ROC or P3-ROC, you should reboot."
echo ""
echo "      When you are done, check your home folder for a"
echo "      'pinball' folder. In there is the folders you"
echo "                    need to get started."
echo ""
echo "   For more information, visit docs.missionpinball.com"
echo ""
echo "                     Happy pinballing!"
echo ""
read -p "Do you want to reboot now? (y or n)" -n 1 -r REBOOTREPLY
echo    # (optional) move to a new line
if [[ $REBOOTREPLY = "y" ]]; then
  read -p "Are you sure you want to reboot? (y or n)" -n 1 -r REBOOTREPLYCONFIRM
  echo    # (optional) move to a new line
  if [[ $REBOOTREPLYCONFIRM = "y" ]]; then
    sudo shutdown -r now
  else
    echo "REMEMBER TO REBOOT BEFORE YOU TRY TO USE THE GAME"
  fi
else
  echo "REMEMBER TO REBOOT BEFORE YOU TRY TO USE THE GAME"
fi
